---
- include_tasks: nextcloud.yml
  when: '"nextcloud-client" in ubuntu.packages.additional.desktop'
- include_tasks: vagrant.yml
  when: '"vagrant" in ubuntu.packages.additional.desktop'
- include_tasks: staruml.yml
  when: '"staruml" in ubuntu.packages.additional.desktop'
- include_tasks: pycharm.yml
  when: '"pycharm" in ubuntu.packages.additional.desktop'
