---
- name: Ensure Nextcloud client is installed
  get_url:
    url: https://download.nextcloud.com/desktop/releases/Linux/latest
    dest: "/home/{{ ubuntu.user.name }}/Downloads"
    owner: "{{ ubuntu.user.name }}"
    group: "{{ ubuntu.user.name }}"
    mode: 0755
    force: False
  register: nextcloud_client

- name: Ensure Nextcloud start menu entry is added or adapted
  template:
    src: nextcloud.desktop
    dest: "~{{ ubuntu.user.name }}/.local/share/applications/nextcloud.desktop"
    owner: "{{ ubuntu.user.name }}"
    group: "{{ ubuntu.user.name }}"
    mode: 0755
