---
- name: Install ubuntu packages
  hosts: all
  roles:
    - packages
  become: true

- name: Install additional desktop packages
  hosts: desktop
  roles:
    - additional_desktop_apps
  become: true

- name: Setup user
  hosts: all
  roles:
    - user
  become: true

- name: setup user settings
  hosts: all
  roles:
    - shell
  become: true
  become_user: "{{ ubuntu.user.name }}"
  tags: user_settings

