---
- name: Install ubuntu packages
  hosts: all
  roles:
    - packages
  become: true

- name: Install additional desktop packages
  hosts: desktop
  roles:
    - additional_desktop_apps
  become: true

