---
# Stuff common for all hosts
- name: apply common configuration to all nodes
  hosts:
    - all

  roles:
    - common
  become: true
  become_user: root

- name: Configuration for Denephor
  hosts:
    - Denephor

  roles:
    - Denephor
  become: true
  become_user: root

  #tasks:
    #import_tasks: roles/common/tasks/copy_files.yml

    #import_tasks: roles/common/tasks/restart_services.yml
