---
- name: Update apt Cache
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Installing ubuntu packages
  apt:
    name: "{{ ubuntu.packages.common | union(ubuntu.packages.special) | union(ubuntu.packages.host) }}"
    state: present

# TODO: dbeaver
# TODO: PyCharm
# TODO: Vivaldi
# TODO: vagrant
# TODO: staruml
# TODO: ohmyzsh

